### ISSUE TITLE
release v1.4 contail old binary

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/mtb-daemon#14]
In release v1.4 is in assets zip file, which contail old .exe binary file. In console is shown version 1.2, when launched.
Also don't know new module type MTB-UNIS.

![mtb_daemon_old_in_release](https://github.com/kmzbrnoI/mtb-daemon/assets/17301903/202d4ff6-1ec8-4f27-af5c-8b4e430905a2)

**Comment by horacekj** [comment]
Sorry for that. Correct exe reuploaded.
