### ISSUE TITLE
If module on bus but not in config application crash.

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/mtb-daemon#15]
When mtb-daemon recognize new module function:
DaemonCoreApplication::moduleGotInfo(uint8_t addr, Mtb::ModuleInfo info);
is called in file main.cpp (line 256).

```
void DaemonCoreApplication::moduleGotInfo(uint8_t addr, Mtb::ModuleInfo info) {
	if ((modules[addr] != nullptr) && (static_cast<size_t>(modules[addr]->moduleType()) != info.type)) {
		log("Detected module "+QString::number(addr)+" type & stored module type mismatch! Forgetting config...",
		    Mtb::LogLevel::Warning);
		modules[addr] = this->newModule(info.type, addr);
	}

	modules[addr]->mtbBusActivate(info);
}
```

In this function, **if** statement is resolved as "false", because **modules[addr]** is **nullptr**.
Then statement:
`modules[addr]->mtbBusActivate(info);`
result in access violation.

This code snippet can resolve issue. Paste it before module activation:
```
    if (modules[addr] == nullptr)
        modules[addr] = this->newModule(info.type, addr);
```

**Comment by horacekj** [comment]
Fixed.
